import type { components } from '@/types/generated/schema';

// src/types/ is the only layer allowed to touch `components['schemas']`
// (docs/FRONTEND-CONVENTIONS.md §5) — everything else imports these named types.
// docs/plans/mcp-oauth/task-09-admin-connected-apps-ui.md: wire shapes for the admin
// "Connected apps" page, generated by task-08's codegen from `GET /api/v1/oauth/clients`.
export type ConnectedAppDto = components['schemas']['ConnectedApp'];
export type ConnectedAppsResponseDto = components['schemas']['ConnectedAppsResponse'];
